### ISSUE TITLE
Feature request: paired parameters

### ISSUE THREAD

**Issue by janusvm** [lpil/formal#3]
It would be nice to have a built-in way of validating two (or more) `form.parameter`s together.

For example, in a signup form, I might have a "password" and "confirm-password" field and want to validate that they are equal. Currently, I can do this by inspecting the coerced value *after* validation and hand-rolling my own second-pass validation, but it would be nicer with something similar to `parameter` + `field` for it in the first pass.

**Comment by lpil** [comment]
How would that work?

**Comment by janusvm** [comment]
Not entirely sure. Perhaps something similar to `parameter` and `field` like

```gleam
form.decoding({
  use <- form.paired_parameters
  ...
})
...
|> form.paired_fields(
  // with something in here that compares the two
)
```

**Comment by lpil** [comment]
I think it might be possible to implement it with something like this:

```gleam
    |> form.paired_fields(
      "password",
      form.string
        |> form.and(form.must_not_be_empty)
        |> form.and(form.must_be_string_longer_than(7))
      "password-confirmation",
      form.string,
      fn(password, confirmation) {
        case password == confirmation {
          True -> #(Ok(Nil), Ok(Nil))
          False -> #(Ok(Nil), Error("must match the password"))
        }
      }
    )
```

But I'm not convinced this is better than doing the checking outside of `formal` with normal Gleam code.

**Comment by janusvm** [comment]
After having played around with it some more, I think I'm inclined to agree, actually.
It's simple enough to return a new `Form` with errors based on the parsed values from `form.finish`, and the two-stage flow feels natural enough (at least for a signup form) that the fiddling to add more validation errors to an already errored form isn't necessary.

Closing this.

**Comment by lpil** [comment]
Thank you
